const REGISTERED = "REGISTERED";
const REGISTER_ERROR = "REGISTER_ERROR";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_ERROR = "LOGIN_ERROR";
const LOGGED_OUT = "LOGGED_OUT";
const NAVIGATE_TO_LOGIN = "NAVIGATE_TO_LOGIN";

export {
  REGISTERED,
  REGISTER_ERROR,
  LOGIN_SUCCESS,
  LOGIN_ERROR,
  LOGGED_OUT,
  NAVIGATE_TO_LOGIN,
};
