const ORDER_ACCEPTED = "ORDER_ACCEPTED";
const ORDER_DETAILS_CLOSED = "ORDER_DETAILS_CLOSED";
const NEW_INGREDIENT_IN_ORDER = "NEW_INGREDIENT_IN_ORDER";
const DELETED_FILLING_IN_ORDER = "DELETED_INGREDIENT_IN_ORDER";
const FILLING_MOVED = "FILLING_MOVED";

export {
  ORDER_ACCEPTED,
  ORDER_DETAILS_CLOSED,
  NEW_INGREDIENT_IN_ORDER,
  DELETED_FILLING_IN_ORDER,
  FILLING_MOVED,
};
