const RESET_EMAIL_SENT = "RESET_EMAIL_SENT";
const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
const PASSWORD_RESET_ERROR = "PASSWORD_RESET_ERROR";
const RESET_PASSWORD_OPENED = "RESET_PASSWORD_OPENED";

export {
  RESET_EMAIL_SENT,
  PASSWORD_RESET_SUCCESS,
  PASSWORD_RESET_ERROR,
  RESET_PASSWORD_OPENED,
};
